name: Update dependencies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dep:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update swift package dependencies
        run: swift package update
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github action
          author_email: action@github.com
          new_branch: dep-update
          message: "fix: Update dependencies"
          add: .
          push: true
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "fix: Update dependencies"
