name: Update dependencies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dep:
    name: Update dependencies
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update swift package dependencies
        uses: GetSidetrack/action-xcodeproj-spm-update@main
        with:
          forceResolution: true
          failWhenOutdated: false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          commit-message: "fix: Update dependencies"
          title: "fix: Update dependencies"
          body: "Update dependencies"
          base: "main"
          token: ${{secrets.RELEASE_TOKEN}}
