name: Automated release
on: push

jobs:
  build:
    name: Generate macOS app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: ./scripts/ci_certificate.sh
      - name: Build app
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: fastlane build
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
  create-release:
    if: ${{ github.event.pusher.name != 'github action' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get next version
        id: version
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main
          dry_run: true
      - run: echo Released ${{ steps.version.outputs.new_release_version }}
      - uses: sirily11/ios-bump-version@master
        with:
          version: ${{ steps.version.outputs.new_release_version }}
          build-number: ${{github.run_attempt }}
      - uses: EndBug/add-and-commit@v9
        name: Add and commit version changed
        with:
          message: "Release ${{ steps.version.outputs.new_release_version }}"
          push: false
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main
          dry_run: false
        if: ${{ github.ref == 'refs/heads/main' }}
      - uses: EndBug/add-and-commit@v9
        name: Push release commit
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Push release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
        if: ${{ github.ref == 'refs/heads/main' }}
